// Playwright MCP function. Requires the isolated server on port 8877.
async (page) => {
  const q=await page.context().newPage();
  const size=page.viewportSize()||{width:390,height:844},mobile=size.width<768;
  q.on('dialog', d=>d.accept());
  const assert=(ok,message)=>{if(!ok)throw new Error(message);};
  try {
    await q.setViewportSize(size);
    await q.goto('http://127.0.0.1:8877/trading_trainer.html?code=sh600000');
    await q.waitForFunction(()=>document.querySelector('#code').value.includes('sh600000'));
    const metadata=await (await q.request.get('http://127.0.0.1:8877/api/trainer/dates?code=sh600000')).json();
    const dates=metadata.dates;
    assert(dates.length>=2,'Need two cached trading days');
    await q.locator('#startRandom').uncheck();
    await q.locator('#startDate').fill(dates.at(-2));
    await q.locator('#start').click();
    await q.waitForFunction(()=>typeof state!=='undefined'&&state?.minute_points.length>0);
    await q.locator('#openBuy').click();
    await q.locator('#manualOrderType').selectOption('limit');
    await q.locator('#manualLimitPrice').fill('1');
    await q.locator('#manualShares').fill('100');
    await q.locator('#manualSubmit').click();
    await q.waitForFunction(()=>state.account.reserved_cash>0);
    const frozen=await q.evaluate(()=>state.account.reserved_cash);
    await q.locator('#openManage').click();
    await q.locator('#pendingManage').getByRole('button',{name:'撤单'}).click();
    await q.waitForFunction(()=>state.account.reserved_cash===0);
    await q.locator('#closeModal').click();
    await q.locator('#openBuy').click();
    await q.locator('#manualOrderType').selectOption('market');
    await q.locator('#manualShares').fill('100');
    await q.locator('#manualSubmit').click();
    await q.waitForFunction(()=>state.account.locked_shares===100);
    await q.locator('#openSell').click();
    assert(!await q.locator('#manualSubmit').isEnabled(),'T+1 sell was enabled');
    await q.locator('[data-trade-tab=condition]').click();
    await q.locator('#triggerValue').fill('1');
    await q.locator('#conditionShares').fill('100');
    await q.locator('#conditionSubmit').click();
    await q.waitForFunction(()=>state.conditional_orders.length>0);
    await q.locator('#openManage').click();
    await q.locator('#managePane').getByRole('button',{name:'撤销条件单'}).click();
    await q.waitForFunction(()=>state.conditional_orders[0].status==='cancelled');
    await q.keyboard.press('Escape');
    const snapshot=()=>JSON.stringify({account:state.account,minutes:state.minute_points,orders:state.orders,progress:state.progress});
    const before=await q.evaluate(snapshot);
    await q.locator('[data-shell-action=theme]').click();
    await q.locator('[data-shell-action=density]').click();
    if(mobile) await q.locator('.wb-chart-tabs').getByRole('tab',{name:'分时',exact:true}).click();
    assert(before===await q.evaluate(snapshot),'Presentation changed trading state');
    await q.locator('[data-shell-action=theme]').click();
    await q.locator('[data-shell-action=density]').click();
    await q.locator('#closeDay').click();
    await q.waitForFunction(()=>state.progress.day_complete);
    await q.locator('#nextDay').click();
    await q.waitForFunction(()=>state.account.available_shares===100);
    await q.locator('#openSell').click();
    await q.locator('#manualShares').fill('100');
    await q.screenshot({path:'output/ui-qa/trade-'+(mobile?'mobile':'desktop')+'-final.png'});
    await q.locator('#manualSubmit').click();
    await q.waitForFunction(()=>state.account.total_shares===0);
    const account=await q.evaluate(()=>state.account);
    const cutoff=await q.evaluate(()=>({date:state.date,time:state.time,high:state.daily_bars.at(-1).high}));
    await q.locator((mobile?'.wb-bottom':'.wb-sidebar')+' a[href*="stock_journal"]').click();
    await q.waitForURL('**/stock_journal.html?**');
    await q.waitForFunction(()=>typeof market!=='undefined'&&market?.bars.length>0);
    const last=await q.evaluate(()=>market.latest);
    assert(last.date===cutoff.date&&last.high===cutoff.high,'Journal exposed future data');
    await q.locator('#newCaseButton').click();
    await q.locator('#caseTitle').fill('UI自动验收');
    await q.locator('#createCase').click();
    await q.waitForFunction(()=>selectedCaseId!==null);
    if(mobile) await q.getByRole('button',{name:'＋ 快速记录'}).click();
    await q.locator('#reason').fill('仅记录当前模拟时刻可见证据');
    const submit=await q.locator('#saveEntry').boundingBox();
    if(mobile) assert(submit.y+submit.height<=size.height,'Journal submit outside viewport');
    await q.locator('#saveEntry').click();
    await q.waitForFunction(()=>entries.length===1&&!document.querySelector('dialog[open]'));
    await q.locator('#symbolContextLink').click();
    await q.waitForURL('**/symbol.html?**');
    await q.locator('a[data-tab=minute]').click();
    await q.waitForURL('**/minute_view.html?**');
    await q.waitForFunction(()=>typeof current!=='undefined'&&current?.points.length===1);
    const minute=await q.evaluate(()=>({points:current.points.length,dates:current.dates}));
    return {frozen,account,cutoff,minute,tPlusOne:true,cancellation:true,presentationInvariant:true,journalSaved:true};
  } finally {await q.close();}
}
